"""Initial migration

Revision ID: a826cd327924
Revises: 
Create Date: 2024-02-16 21:05:51.842627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a826cd327924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pelicula', schema=None) as batch_op:
        batch_op.alter_column('Imagen',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Rol', sa.String(length=20), nullable=False))
        batch_op.drop_constraint('usuario_ibfk_1', type_='foreignkey')
        batch_op.drop_column('Rol_idRol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Rol_idRol', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('usuario_ibfk_1', 'rol', ['Rol_idRol'], ['idRol'])
        batch_op.drop_column('Rol')

    with op.batch_alter_table('pelicula', schema=None) as batch_op:
        batch_op.alter_column('Imagen',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
